# -*- coding: utf-8 -*-
"""QN 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Wn-kBjkuzCwtD7R34TqVIKYmj3hnwMz
"""

str1 = input("Enter first string :")
str2 = input("Enter second string :")

if(str1 == str2):
  print("Given two strings are equal")
else:
  print("Given two strings are not equal")