# -*- coding: utf-8 -*-
"""QN 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Wn-kBjkuzCwtD7R34TqVIKYmj3hnwMz
"""

num1 = int(input("Enter first number :"))
num2 = int(input("Enter second number :"))
sum = num1 + num2
print("The sum of",num1,"and",num2,"is",sum)