# -*- coding: utf-8 -*-
"""QN 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Wn-kBjkuzCwtD7R34TqVIKYmj3hnwMz
"""

num = int(input("Enter the number :"))
sqrt = num**.5
print("The square root of",num,"is",sqrt)