# -*- coding: utf-8 -*-
"""QN 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Wn-kBjkuzCwtD7R34TqVIKYmj3hnwMz
"""

base = int(input("Enter the base : "))
height = int(input("Enter the height : "))
area = .5*base*height
print("The area of triangle is ",area,"square units")