# -*- coding: utf-8 -*-
"""QN 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Wn-kBjkuzCwtD7R34TqVIKYmj3hnwMz
"""

c = int(input("Enter the temperature in celsius :"))
f = (c*9/5)+32
print(c,"°C =",f,"°F")