# -*- coding: utf-8 -*-
"""QN 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Wn-kBjkuzCwtD7R34TqVIKYmj3hnwMz
"""

num = int(input("Enter a number:"))

if num>0:
  print(num,"is a positive number")
elif num<0:
  print(num,"is a negative number")
else:
  print(" Given number is 0")