# -*- coding: utf-8 -*-
"""QN 7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Wn-kBjkuzCwtD7R34TqVIKYmj3hnwMz
"""

a1 = int(input("Enter the first number :"))
a2 = int(input("Enter the second number :"))
a3 = int(input("Enter the thrid number :"))

if a1>a2:
  if a1>a3:
    print(a1,"is greater than",a2,"and",a3)
  else:
    print(a3,"is greater than",a1,"and",a2)

else:
  if a2>a3:
    print(a2,"is greater than",a1,"and",a3)
  else:
    print(a3,"is greater than",a1,"and",a2)